export const api_base_url = import.meta.env.VITE_API_BASE_URI;

export const topBannerImages = [
  {
    id:101,
    src:'/images/electronics/topbanner/Oneplus.avif',
    alt:'oneplus'
  },
  {
    id:102,
    src:'/images/electronics/topbanner/Purifier.avif',
    alt:'Purifier'
  },
  {
    id:103,
    src:'/images/electronics/topbanner/Watch.avif',
    alt:'Watch'
  },
  {
    id:104,
    src:'/images/electronics/topbanner/Pixel-XL.avif',
    alt:'Pixel-XL'
  }
]

export const hotDealsImages = [
  {
    id:105,
    src:'/images/electronics/hotDeals/vivo.webp',
    alt:'vivo'
  },
  {
    id:106,
    src:'/images/electronics/hotDeals/Printers.webp',
    alt:'Printers'
  },
  {
    id:107,
    src:'/images/electronics/hotDeals/Tablets.webp',
    alt:'Tablets'
  },
  {
    id:108,
    src:'/images/electronics/hotDeals/Speakers.webp',
    alt:'Speakers'
  },
  {
    id:109,
    src:'/images/electronics/hotDeals/s6.jpg',
    alt:'S6 tab'
  },
  {
    id:110,
    src:'/images/electronics/hotDeals/oneplus_pad.jpg',
    alt:'oneplus_pad'
  },
  {
    id:111,
    src:'/images/electronics/hotDeals/redmi_pad.jpg',
    alt:'redmi_pad'
  },
  {
    id:112,
    src:'/images/electronics/hotDeals/lenovo_tab.png',
    alt:'lenovo_tab'
  }
]

export const SecBannerImages = [
  {
    id:113,
    src:'/images/electronics/secondBanner/s21_fe.jpg',
    alt:'s21_fe'
  },
  {
    id:114,
    src:'/images/electronics/secondBanner/iqoo.jpg',
    alt:'iqoo'
  },
  {
    id:115,
    src:'/images/electronics/secondBanner/realme_gt.jpg',
    alt:'realme_gt'
  },
  {
    id:116,
    src:'/images/electronics/secondBanner/xiami14.jpg',
    alt:'xiami14'
  },
  {
    id:117,
    src:'/images/electronics/secondBanner/narzo70.jpg',
    alt:'narzo70'
  }
]

export const ExploreImages = [
  {
    id:121,
    src:'/images/electronics/explore/acer.jpg',
    alt:'acer'
  },
  {
    id:122,
    src:'/images/electronics/explore/asus.jpg',
    alt:'asus'
  },
  {
    id:123,
    src:'/images/electronics/explore/dell.jpg',
    alt:'dell'
  },
  {
    id:124,
    src:'/images/electronics/explore/ipad.png',
    alt:'ipad'
  },
  {
    id:125,
    src:'/images/electronics/explore/s6.png',
    alt:'s6'
  },
  {
    id:126,
    src:'/images/electronics/explore/m10.jpg',
    alt:'m10'
  },
  {
    id:127,
    src:'/images/electronics/explore/oneplus.jpg',
    alt:'oneplus'
  },
  {
    id:128,
    src:'/images/electronics/explore/noise.jpg',
    alt:'noise'
  },
  {
    id:129,
    src:'/images/electronics/explore/realme.jpg',
    alt:'realme'
  },
  {
    id:130,
    src:'/images/electronics/explore/firebolt.jpg',
    alt:'firebolt'
  },
  {
    id:131,
    src:'/images/electronics/explore/mazfit.jpg',
    alt:'mazfit'
  },
  {
    id:132,
    src:'/images/electronics/explore/boat.jpg',
    alt:'boat'
  }
]